### ISSUE TITLE
Jenkins global "noProxyHost" is not taken into consideration

### ISSUE THREAD

**Issue by clemlesne** [jfrog/jenkins-artifactory-plugin#323]
**Describe the bug**

I have a Jenkins instance with a `proxy` and a `noProxyHost` variables defined. I use the Artifactory plugin. When I execute the plugin, the proxy is used. The issue it that my host is excluded in `noProxyHost` but the plugin tried to pass through my proxy.

**To Reproduce**

Create a Jenkins instance with a JCasC:

```yaml
jenkins:
  proxy:
    name: my-proxy
    port: 8080
    noProxyHost: |
      *.my-company.com
unclassified:
  artifactoryBuilder:
    artifactoryServers:
    - serverId: my-server-ref-in-config
      artifactoryUrl: https://artifactory.my-company.com/artifactory
      deployerCredentialsConfig:
        credentialsId: token-my-server
      resolverCredentialsConfig:
        credentialsId: token-my-server
```

Execute a Groovy pipeline based on:

```groovy
private static final String ARTIFACTORY_SERVER_ID = 'my-server-ref-in-config'
private static final String ARTIFACTORY_DEPS_REPO = 'virtual_my-repo'
private static final String ARTIFACTORY_RELEASE_REPO = 'my-repo'

// Setup Artifactory build
this.artifactoryServer = this.steps.Artifactory.server(Artifactory.ARTIFACTORY_SERVER_ID)
this.artifactoryBuild = this.steps.Artifactory.newGradleBuild()
this.artifactoryBuild.useWrapper = true

// Resolve dependencies into this repo
this.artifactoryBuild.resolver(server: this.artifactoryServer, repo: Artifactory.ARTIFACTORY_DEPS_REPO)

this.artifactoryBuild.deployer(server: this.artifactoryServer, repo: Artifactory.ARTIFACTORY_RELEASE_REPO)

def buildInfo = this.artifactoryBuild.run(
  rootDir: '.',
  buildFile: 'build.gradle',
  tasks: 'assemble artifactoryPublish -x check -x test --build-cache --stacktrace')

// Collect the environment variables to build info
buildInfo.env.capture = true

// Ready to compile & deploy the artefacts!
this.artifactoryBuild.deployer.deployArtifacts buildInfo
// Publish the build infos
this.artifactoryServer.publishBuildInfo buildInfo
```

**Expected behavior**

The plugin should take into consideration the `noProxyHost` in order to contact directly the client without the proxy.

**Versions**

- Jenkins version: 2.235.5
- Jenkins Artifactory plugin version: 3.7.3
- Jenkins operating system: Redhat UBI 8.2
- Artifactory Server Version: EnterpriseX license 7.5.5

**Additional context**

This is critical for me. Without this, all my pipeline for all my components doesn't work.
