### ISSUE TITLE
artifactory plugin 3.11.0 not compatible with JCasC?

### ISSUE THREAD

**Issue by ewelinawilkosz** [jfrog/jenkins-artifactory-plugin#476]
**Describe the bug**
After upgrading artifactory plugin to version 3.11.0 (and Jenkins to 2.277.4), Jenkins Configuration as Code plugin no longer accept artifactory plugin configuration - it throws a stacktrace

When trying to configure manually, and exporting the configuration (Manage Jenkins > Configuration as Code > View Configuration) I can see errors:

```
unclassified:
  artifactoryBuilder:
    artifactoryServers: |-
      FAILED TO EXPORT
      org.jfrog.hudson.ArtifactoryBuilder$DescriptorImpl#artifactoryServers: No configurator found for type class org.jfrog.hudson.ArtifactoryServer
```

with older version, 3.10.6 (Jenkins version 2.277.2) it looks correct:

```
unclassified:
  artifactoryBuilder:
    artifactoryServers:
    - artifactoryUrl: "http://(...)"
      bypassProxy: false
      connectionRetry: 3
      deployerCredentialsConfig:
(...)

```

**To Reproduce**
Try to configure artifactory on Jenkins manually and check exported JCasC config

**Expected behavior**
as in a fragment of code shared above

**Screenshots**
n/a

**Versions**
- Jenkins Artifactory plugin version: 3.11.0
- Jenkins operating system: 2.277.4
- Artifactory Version: n/a

**Additional context**
n/a
