### ISSUE TITLE
JFrog Artifactory URL is not getting updated properly

### ISSUE THREAD

**Issue by manmadhang** [jfrog/jenkins-artifactory-plugin#532]
**Describe the bug**
We are experiencing strange issue on artifactory plugin updated with 3.12.5

We have deployed our Jenkins instance on Kubernetes environment as JCasC.  In our configmap manifest file have defined as follows, while applying our configmap, the “JFrog Artifactory URL” is not getting updated properly.  Seems by default it is enabled with Instance ID.

**To Reproduce**
_configmap Example:_
```
artifactoryBuilder:
          useCredentialsPlugin: false
          jfrogInstances:
            - instanceId: "ARTIFACTORY"
              platformUrl: https://artifactory.xyz.com
```

**Expected behavior**
The JFrog Artifactory URL should update as like JFrog Platform URL

**Screenshots**
![Screenshot 2021-07-21 144024](https://user-images.githubusercontent.com/33718150/126464961-4660f31f-dc80-4307-b717-070a30be451d.png)

**Versions**
- Jenkins Artifactory plugin version: 3.12.5
- Jenkins operating system: 2.289.1
- Artifactory Version: 7.10.2

**Additional context**
